list_ = []
change_in_price_algo= list_.append(0)
change_in_price_ape= list_.append(0)
change_in_price_atom = list_.append(0)
change_in_price_avax = list_.append(0)
change_in_price_banano = list_.append(0)
change_in_price_bch = list_.append(0)
change_in_price_bitcoin = list_.append(0)
change_in_price_bnb = list_.append(0)
change_in_price_cake = list_.append(0)
change_in_price_cardano = list_.append(0)
change_in_price_chainlink= list_.append(0)
change_in_price_cronos = list_.append(0)
change_in_price_dogecoin= list_.append(0)
change_in_price_eos = list_.append(0)
change_in_price_ethereum = list_.append(0)
change_in_price_litecoin= list_.append(0)
change_in_price_mana= list_.append(0)
change_in_price_matic= list_.append(0)
change_in_price_monero= list_.append(0)
change_in_price_polkadot= list_.append(0)
change_in_price_sand = list_.append(0)
change_in_price_shiba= list_.append(0)
change_in_price_solana = list_.append(0)
change_in_price_tezos = list_.append(0)
change_in_price_trx= list_.append(0)
change_in_price_uniswap= list_.append(0)
change_in_price_xlm= list_.append(0)
change_in_price_xrp = list_.append(0)
change_in_price_nano = list_.append(0)
change_in_price_kaspa = list_.append(0)
change_in_price_bat = list_.append(list_.append(0))

print(len(list_))

